"""SAC actor → Arduino-PROGMEM weight exporter.

Loads a trained SAC zip, extracts ONLY the actor mean head
(``latent_pi`` Linears + ``mu``), drops the critics and ``log_std``,
and emits a single self-contained C++ header containing:

  * float32 PROGMEM weight tables (W1, B1, W2, B2, W_OUT, B_OUT)
  * layer dim ``constexpr`` constants
  * a 64-entry tanh LUT with linear interpolation (saturating ±1
    outside ``[-3, +3]``) so the AVR doesn't pay for ``tanhf``
  * ``predict_motors(...)`` forward pass using the LUT
  * 10 self-test (obs, expected_action) pairs, where the expected
    action is generated by running the *same* LUT-based forward
    pass in Python — so a firmware verify check should report
    sub-1e-5 max delta for a healthy port

Usage:

    python export_weights.py --model sac_actor_v4.zip --output neural_net_v4.h
"""

from __future__ import annotations

import os

os.environ.setdefault("KMP_DUPLICATE_LIB_OK", "TRUE")

# Import torch BEFORE numpy on Windows: importing numpy first can
# trigger a DLL-search-order race against torch's fbgemm.dll
# (WinError 127). Mirrors the order used by train_dqn.py.
import torch

import argparse
from pathlib import Path
from typing import Callable

import numpy as np
from stable_baselines3 import SAC


# ----- Weight extraction ----------------------------------------------------

def extract_actor_weights(model) -> dict[str, np.ndarray]:
    """Return {W1,B1,W2,B2,W_OUT,B_OUT} as np.float32. Handles two
    actor layouts:

    * SAC: ``actor.latent_pi`` is a Sequential of (Linear, ReLU,
      Linear, ReLU); ``actor.mu`` is the final Linear that produces
      the pre-tanh mean (tanh is applied in the policy's forward).
    * TD3: ``actor.mu`` is a Sequential containing the full MLP
      (Linear, ReLU, Linear, ReLU, Linear, Tanh) — three Linears.

    Either way we pull out the three Linear layers in order.
    """
    actor = model.policy.actor
    if hasattr(actor, "latent_pi"):
        linears = [m for m in actor.latent_pi if isinstance(m, torch.nn.Linear)]
        if len(linears) != 2:
            raise RuntimeError(
                f"expected 2 hidden Linear layers in actor.latent_pi, "
                f"got {len(linears)}; net_arch differs from [H1, H2]?"
            )
        L1, L2 = linears
        LOUT = actor.mu
    else:
        linears = [m for m in actor.mu if isinstance(m, torch.nn.Linear)]
        if len(linears) != 3:
            raise RuntimeError(
                f"expected 3 Linear layers in TD3 actor.mu, got "
                f"{len(linears)}; net_arch differs from [H1, H2]?"
            )
        L1, L2, LOUT = linears

    def n(t: torch.Tensor) -> np.ndarray:
        return t.detach().cpu().numpy().astype(np.float32)

    return {
        "W1": n(L1.weight), "B1": n(L1.bias),
        "W2": n(L2.weight), "B2": n(L2.bias),
        "W_OUT": n(LOUT.weight), "B_OUT": n(LOUT.bias),
    }


# ----- Tanh LUT -------------------------------------------------------------

def make_tanh_lut(n_entries: int = 64,
                  x_min: float = -3.0,
                  x_max: float = 3.0) -> np.ndarray:
    """64 evenly spaced samples of tanh on [x_min, x_max] inclusive.
    The Python lookup below mirrors the C++ code byte-for-byte so
    self-test pairs land at < 1e-5 max delta on the firmware."""
    return np.tanh(np.linspace(x_min, x_max, n_entries)).astype(np.float32)


def fast_tanh_lut(x: float, lut: np.ndarray,
                  x_min: float, x_max: float) -> float:
    """Python mirror of the firmware's ``fast_tanh``."""
    if x <= x_min:
        return -1.0
    if x >= x_max:
        return 1.0
    n = lut.shape[0]
    dx = (x_max - x_min) / (n - 1)
    t = (x - x_min) / dx
    i = int(t)
    if i < 0:
        i = 0
    if i > n - 2:
        i = n - 2
    frac = t - i
    return float(lut[i] + (lut[i + 1] - lut[i]) * frac)


# ----- Self-test forward pass ----------------------------------------------

def _relu(x: np.ndarray) -> np.ndarray:
    return np.maximum(0.0, x)


def python_forward_with_lut(
    obs: np.ndarray, weights: dict[str, np.ndarray],
    lut: np.ndarray, lut_x_min: float, lut_x_max: float,
) -> np.ndarray:
    """Reproduces the firmware's forward pass, including LUT tanh."""
    h1 = _relu(weights["W1"] @ obs + weights["B1"])
    h2 = _relu(weights["W2"] @ h1 + weights["B2"])
    out_pre = weights["W_OUT"] @ h2 + weights["B_OUT"]
    return np.array(
        [fast_tanh_lut(float(v), lut, lut_x_min, lut_x_max)
         for v in out_pre],
        dtype=np.float32,
    )


def make_self_test_pairs(
    weights: dict[str, np.ndarray],
    lut: np.ndarray, lut_x_min: float, lut_x_max: float,
    input_dim: int, n_pairs: int = 10, seed: int = 4242,
) -> tuple[np.ndarray, np.ndarray]:
    """10 deterministic (obs, expected_action) pairs spanning the obs
    domain. obs[0:3] ∈ [0, 1] (front/left/right normalised distances),
    obs[3] ∈ {-1, 0, +1} (last_seen_dir), obs[4:6] ∈ {0, 1} (line
    sensors) — same as MiniSumoEnv's observation_space."""
    rng = np.random.default_rng(seed)
    obs = np.zeros((n_pairs, input_dim), dtype=np.float32)
    obs[:, 0:3] = rng.uniform(0.0, 1.0, size=(n_pairs, 3))
    obs[:, 3] = rng.choice([-1.0, 0.0, 1.0], size=n_pairs)
    obs[:, 4:6] = rng.choice([0.0, 1.0], size=(n_pairs, 2))
    if input_dim >= 8:
        # prev_left, prev_right ∈ [-1, +1] — last raw policy output.
        obs[:, 6:8] = rng.uniform(-1.0, 1.0, size=(n_pairs, 2))
    if input_dim >= 9:
        # engagement_timer ∈ [0, 1] — close-front consecutive ticks / 30.
        obs[:, 8] = rng.uniform(0.0, 1.0, size=n_pairs)
    if input_dim >= 10:
        # yaw_rate_proxy ∈ [-1, +1] — decayed (left - right) accumulator.
        obs[:, 9] = rng.uniform(-1.0, 1.0, size=n_pairs)
    if input_dim >= 11:
        # front_ir_delta ∈ [-1, +1] — (front_norm - prev_front_norm) * 2,
        # clipped. Negative = closing, positive = receding.
        obs[:, 10] = rng.uniform(-1.0, 1.0, size=n_pairs)
    if input_dim >= 12:
        # lateral_ir_delta ∈ [-1, +1] — same formula on min(left, right).
        obs[:, 11] = rng.uniform(-1.0, 1.0, size=n_pairs)
    actions = np.stack([
        python_forward_with_lut(obs[k], weights, lut, lut_x_min, lut_x_max)
        for k in range(n_pairs)
    ]).astype(np.float32)
    return obs, actions


# ----- Header formatting ---------------------------------------------------

def _fmt_float(v: float) -> str:
    return f"{v:.7e}f"


def _matrix_lines(mat: np.ndarray) -> str:
    rows = []
    for row in mat:
        rows.append("    {" + ", ".join(_fmt_float(v) for v in row) + "},")
    return "\n".join(rows)


def _vector_line(vec: np.ndarray) -> str:
    return "    " + ", ".join(_fmt_float(v) for v in vec)


def render_header(
    weights: dict[str, np.ndarray],
    lut: np.ndarray, lut_x_min: float, lut_x_max: float,
    self_test_obs: np.ndarray, self_test_actions: np.ndarray,
) -> str:
    W1, B1 = weights["W1"], weights["B1"]
    W2, B2 = weights["W2"], weights["B2"]
    W_OUT, B_OUT = weights["W_OUT"], weights["B_OUT"]
    h1, in_dim = W1.shape
    h2, _ = W2.shape
    out_dim, _ = W_OUT.shape
    lut_n = lut.shape[0]
    n_self_test = self_test_obs.shape[0]

    # LUT linear-interp worst-case error ≈ h^2/2 * max|tanh''|.
    # h = (x_max - x_min) / (n - 1); max|tanh''| ≈ 0.7699 at x ≈ 0.66.
    h = (lut_x_max - lut_x_min) / (lut_n - 1)
    lut_err = (h * h / 2.0) * 0.7699

    # Format the self-test arrays.
    obs_lines = "\n".join(
        "    {" + ", ".join(_fmt_float(v) for v in self_test_obs[k]) + "},"
        for k in range(n_self_test)
    )
    act_lines = "\n".join(
        "    {" + ", ".join(_fmt_float(v) for v in self_test_actions[k]) + "},"
        for k in range(n_self_test)
    )

    return f"""// Auto-generated by export_weights.py — do not edit by hand.
//
// Deterministic actor (SAC mean head OR TD3 actor.mu):
//   input({in_dim})
//     -> Linear({h1}) ReLU
//     -> Linear({h2}) ReLU
//     -> Linear({out_dim}) tanh
//
// Inputs (must be normalised the same way the env does):
//   [0] front           in [0, 1]   (laser distance / 0.80 m; 1 = no hit)
//   [1] left            in [0, 1]
//   [2] right           in [0, 1]
//   [3] last_seen       in {{-1, 0, +1}}  (left, front, right last detection)
//   [4] line_l          in {{0, 1}}       (rear-left QTR over white border)
//   [5] line_r          in {{0, 1}}       (rear-right QTR over white border)
//   [6] prev_left       in [-1, +1]      (last predict_motors output)
//   [7] prev_right      in [-1, +1]
//   [8] engagement      in [0, 1]        (consecutive close-front ticks / 30)
//   [9] yaw_rate_proxy  in [-1, +1]      (decayed (left - right) accumulator)
//   [10] front_ir_delta  in [-1, +1]     (Δfront_norm × 2, clipped)
//   [11] lateral_ir_delta in [-1, +1]    (Δmin(left, right) × 2, clipped)
//
// Both delta features are temporal derivatives over one 25 Hz tick:
//   negative = enemy approaching that direction, positive = receding.
// Firmware must cache the previous frame's normalised IR readings.
//
// Output (deterministic action):
//   action = tanh(actor.mu(features)) * ACTION_SCALE
// SB3 action_space = [-1, 1] so ACTION_SCALE = 1; emitted as a constant
// for forward compat if the action space ever changes.

#pragma once
#include <avr/pgmspace.h>
#include <math.h>
#include <stdint.h>

namespace mini_sumo_ai {{

constexpr uint8_t INPUT_DIM    = {in_dim};
constexpr uint8_t H1_DIM       = {h1};
constexpr uint8_t H2_DIM       = {h2};
constexpr uint8_t OUTPUT_DIM   = {out_dim};
constexpr float   ACTION_SCALE = 1.0f;

// === Weight tables ====================================================

const float W1[{h1}][{in_dim}] PROGMEM = {{
{_matrix_lines(W1)}
}};
const float B1[{h1}] PROGMEM = {{
{_vector_line(B1)}
}};

const float W2[{h2}][{h1}] PROGMEM = {{
{_matrix_lines(W2)}
}};
const float B2[{h2}] PROGMEM = {{
{_vector_line(B2)}
}};

const float W_OUT[{out_dim}][{h2}] PROGMEM = {{
{_matrix_lines(W_OUT)}
}};
const float B_OUT[{out_dim}] PROGMEM = {{
{_vector_line(B_OUT)}
}};

// === Tanh LUT =========================================================
//
// {lut_n} samples of tanh on [{lut_x_min}, {lut_x_max}], linearly
// interpolated. Worst-case interp error in this range ≈ {lut_err:.4f}
// (h^2/2 * max|tanh''|, h = {h:.5f}). Outside the range we saturate
// at ±1 (hardtanh fallback). Replacing tanhf with this LUT keeps the
// inference loop well under 1 ms on an AVR @ 16 MHz.

constexpr uint8_t TANH_LUT_N     = {lut_n};
constexpr float   TANH_LUT_X_MIN = {lut_x_min}f;
constexpr float   TANH_LUT_X_MAX = {lut_x_max}f;
const float TANH_LUT[{lut_n}] PROGMEM = {{
{_vector_line(lut)}
}};

inline float fast_tanh(float x) {{
    if (x <= TANH_LUT_X_MIN) return -1.0f;
    if (x >= TANH_LUT_X_MAX) return  1.0f;
    const float dx = (TANH_LUT_X_MAX - TANH_LUT_X_MIN)
                     / (float)(TANH_LUT_N - 1);
    const float t = (x - TANH_LUT_X_MIN) / dx;
    int i = (int)t;
    if (i < 0) i = 0;
    if (i > (int)TANH_LUT_N - 2) i = (int)TANH_LUT_N - 2;
    const float frac = t - (float)i;
    const float a = pgm_read_float(&TANH_LUT[i]);
    const float b = pgm_read_float(&TANH_LUT[i + 1]);
    return a + (b - a) * frac;
}}

// === Forward pass =====================================================

inline float relu(float x) {{ return x > 0.0f ? x : 0.0f; }}

inline void predict_motors(
    float front, float left, float right, float last_seen,
    float line_l, float line_r,
    float prev_left, float prev_right,
    float engagement,
    float yaw_rate,
    float front_ir_delta,
    float lateral_ir_delta,
    float &out_left, float &out_right
) {{
    const float in[INPUT_DIM] = {{
        front, left, right, last_seen, line_l, line_r,
        prev_left, prev_right, engagement, yaw_rate,
        front_ir_delta, lateral_ir_delta
    }};

    float h1_act[H1_DIM];
    for (uint8_t i = 0; i < H1_DIM; ++i) {{
        float s = pgm_read_float(&B1[i]);
        for (uint8_t j = 0; j < INPUT_DIM; ++j) {{
            s += pgm_read_float(&W1[i][j]) * in[j];
        }}
        h1_act[i] = relu(s);
    }}

    float h2_act[H2_DIM];
    for (uint8_t i = 0; i < H2_DIM; ++i) {{
        float s = pgm_read_float(&B2[i]);
        for (uint8_t j = 0; j < H1_DIM; ++j) {{
            s += pgm_read_float(&W2[i][j]) * h1_act[j];
        }}
        h2_act[i] = relu(s);
    }}

    float out[OUTPUT_DIM];
    for (uint8_t i = 0; i < OUTPUT_DIM; ++i) {{
        float s = pgm_read_float(&B_OUT[i]);
        for (uint8_t j = 0; j < H2_DIM; ++j) {{
            s += pgm_read_float(&W_OUT[i][j]) * h2_act[j];
        }}
        out[i] = fast_tanh(s) * ACTION_SCALE;
    }}

    out_left  = out[0];
    out_right = out[1];
}}

// === Self-test ========================================================
//
// {n_self_test} (obs, expected_action) pairs computed in Python using
// the SAME LUT-based forward pass this header implements, so any
// non-zero delta in verify_self_test() points at weight corruption,
// PROGMEM read failure, or compiler-level FP reordering — NOT LUT
// approximation. A healthy port should report < 1e-5 max delta.

constexpr uint8_t SELFTEST_N = {n_self_test};
const float SELFTEST_INPUTS[SELFTEST_N][INPUT_DIM] PROGMEM = {{
{obs_lines}
}};
const float SELFTEST_OUTPUTS[SELFTEST_N][OUTPUT_DIM] PROGMEM = {{
{act_lines}
}};

inline float verify_self_test() {{
    float max_delta = 0.0f;
    for (uint8_t k = 0; k < SELFTEST_N; ++k) {{
        float in[INPUT_DIM];
        for (uint8_t j = 0; j < INPUT_DIM; ++j) {{
            in[j] = pgm_read_float(&SELFTEST_INPUTS[k][j]);
        }}
        float ol, orr;
        predict_motors(
            in[0], in[1], in[2], in[3], in[4], in[5],
            in[6], in[7], in[8], in[9], in[10], in[11],
            ol, orr
        );
        const float exp_l = pgm_read_float(&SELFTEST_OUTPUTS[k][0]);
        const float exp_r = pgm_read_float(&SELFTEST_OUTPUTS[k][1]);
        const float dl = fabsf(ol - exp_l);
        const float dr = fabsf(orr - exp_r);
        if (dl > max_delta) max_delta = dl;
        if (dr > max_delta) max_delta = dr;
    }}
    return max_delta;
}}

}}  // namespace mini_sumo_ai
"""


# ----- CLI ------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Export a SAC actor to a self-contained Arduino header.",
    )
    parser.add_argument("--model", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--lut-n", type=int, default=64)
    parser.add_argument("--lut-x-min", type=float, default=-3.0)
    parser.add_argument("--lut-x-max", type=float, default=3.0)
    parser.add_argument("--n-self-test", type=int, default=10)
    parser.add_argument("--seed", type=int, default=4242)
    args = parser.parse_args()

    if not args.model.exists():
        raise FileNotFoundError(args.model)

    print(f"Loading SAC model: {args.model}")
    model = SAC.load(str(args.model), device="cpu")
    weights = extract_actor_weights(model)

    in_dim = weights["W1"].shape[1]
    print(f"  actor: {in_dim} -> {weights['W1'].shape[0]} -> "
          f"{weights['W2'].shape[0]} -> {weights['W_OUT'].shape[0]}")

    lut = make_tanh_lut(args.lut_n, args.lut_x_min, args.lut_x_max)
    obs, acts = make_self_test_pairs(
        weights, lut, args.lut_x_min, args.lut_x_max,
        input_dim=in_dim, n_pairs=args.n_self_test, seed=args.seed,
    )
    header = render_header(
        weights, lut, args.lut_x_min, args.lut_x_max, obs, acts,
    )
    args.output.write_text(header, encoding="ascii")
    print(f"Wrote {args.output} "
          f"({len(header):,} chars, {args.lut_n}-entry LUT, "
          f"{args.n_self_test} self-test pairs)")


if __name__ == "__main__":
    main()
