"""Train SAC from scratch against a real-physics NovaMax opponent through
a 3-tier curriculum.

Phases (each calls model.learn with reset_num_timesteps=False):
    Phase 1: novamax_level=1 (matches agent specs) — 200k steps
    Phase 2: novamax_level=2 (medium)              — 200k steps
    Phase 3: novamax_level=3 (full real spec)      — 200k steps

Outputs land in ``sac_actor_novamax.zip`` / ``_best.zip``,
``neural_net_novamax.h``, and ``checkpoints_novamax/`` so the original
davo_sirad artefacts (sac_actor.zip etc.) stay intact.
"""

from __future__ import annotations

import os
import shutil
from pathlib import Path

# torch must be imported before pybullet on Windows.
os.environ.setdefault("KMP_DUPLICATE_LIB_OK", "TRUE")
import torch  # noqa: F401
from stable_baselines3 import SAC
from stable_baselines3.common.callbacks import CheckpointCallback, CallbackList
import numpy as np

from sumo_env import MiniSumoEnv
from train import (
    NET_ARCH, OBS_DIM, ACTION_DIM,
    WinRateCallback, _matrix_lines, _vector_line,
)


# ---------------------------------------------------------------------------
# Hyperparameters / curriculum
# ---------------------------------------------------------------------------
CURRICULUM: list[tuple[int, int]] = [
    (1, 200_000),   # nerfed NovaMax matches agent specs
    (2, 200_000),   # medium
    (3, 200_000),   # boss / real spec
]
TOTAL_TIMESTEPS = sum(steps for _, steps in CURRICULUM)
SEED = 42

CHECKPOINT_EVERY = 25_000

HERE = Path(__file__).parent
OUTPUT_MODEL = HERE / "sac_actor_novamax.zip"
BEST_MODEL = HERE / "sac_actor_novamax_best.zip"
OUTPUT_HEADER = HERE / "neural_net_novamax.h"
OUTPUT_NPZ = HERE / "sac_actor_novamax_weights.npz"
CHECKPOINT_DIR = HERE / "checkpoints_novamax"


def export_neural_net(model: SAC, path: Path) -> None:
    """Re-emit the standard PROGMEM header from the fine-tuned actor."""
    actor = model.policy.actor
    linears = [m for m in actor.latent_pi if isinstance(m, torch.nn.Linear)]
    if len(linears) != 2:
        raise RuntimeError(
            f"expected 2 hidden Linear layers (net_arch={NET_ARCH}), "
            f"got {len(linears)}"
        )
    L1, L2 = linears
    LOUT = actor.mu

    W1 = L1.weight.detach().cpu().numpy()
    B1 = L1.bias.detach().cpu().numpy()
    W2 = L2.weight.detach().cpu().numpy()
    B2 = L2.bias.detach().cpu().numpy()
    W_OUT = LOUT.weight.detach().cpu().numpy()
    B_OUT = LOUT.bias.detach().cpu().numpy()

    h1, in_dim = W1.shape
    h2, _ = W2.shape
    out_dim, _ = W_OUT.shape
    if (in_dim, h1, h2, out_dim) != (OBS_DIM, NET_ARCH[0], NET_ARCH[1], ACTION_DIM):
        raise RuntimeError(
            f"actor shape mismatch: W1={W1.shape} W2={W2.shape} W_OUT={W_OUT.shape}"
        )

    np.savez(OUTPUT_NPZ, W1=W1, B1=B1, W2=W2, B2=B2, W_OUT=W_OUT, B_OUT=B_OUT)

    header = f"""// Auto-generated by train_novamax.py - do not edit by hand.
// SAC actor (NovaMax fine-tune):
// input(4) -> Linear({h1}) ReLU -> Linear({h2}) ReLU -> Linear({out_dim}) tanh.

#pragma once
#include <avr/pgmspace.h>
#include <math.h>

namespace mini_sumo_ai {{

constexpr uint8_t INPUT_DIM  = {OBS_DIM};
constexpr uint8_t H1_DIM     = {h1};
constexpr uint8_t H2_DIM     = {h2};
constexpr uint8_t OUTPUT_DIM = {out_dim};

const float W1[{h1}][{in_dim}] PROGMEM = {{
{_matrix_lines(W1)}
}};
const float B1[{h1}] PROGMEM = {{
{_vector_line(B1)}
}};

const float W2[{h2}][{h1}] PROGMEM = {{
{_matrix_lines(W2)}
}};
const float B2[{h2}] PROGMEM = {{
{_vector_line(B2)}
}};

const float W_OUT[{out_dim}][{h2}] PROGMEM = {{
{_matrix_lines(W_OUT)}
}};
const float B_OUT[{out_dim}] PROGMEM = {{
{_vector_line(B_OUT)}
}};

inline float relu(float x) {{ return x > 0.0f ? x : 0.0f; }}

inline void predict_motors(
    float front, float left, float right, float last_seen,
    float &out_left, float &out_right
) {{
    const float in[INPUT_DIM] = {{ front, left, right, last_seen }};

    float h1_act[H1_DIM];
    for (uint8_t i = 0; i < H1_DIM; ++i) {{
        float s = pgm_read_float(&B1[i]);
        for (uint8_t j = 0; j < INPUT_DIM; ++j) {{
            s += pgm_read_float(&W1[i][j]) * in[j];
        }}
        h1_act[i] = relu(s);
    }}

    float h2_act[H2_DIM];
    for (uint8_t i = 0; i < H2_DIM; ++i) {{
        float s = pgm_read_float(&B2[i]);
        for (uint8_t j = 0; j < H1_DIM; ++j) {{
            s += pgm_read_float(&W2[i][j]) * h1_act[j];
        }}
        h2_act[i] = relu(s);
    }}

    float out[OUTPUT_DIM];
    for (uint8_t i = 0; i < OUTPUT_DIM; ++i) {{
        float s = pgm_read_float(&B_OUT[i]);
        for (uint8_t j = 0; j < H2_DIM; ++j) {{
            s += pgm_read_float(&W_OUT[i][j]) * h2_act[j];
        }}
        out[i] = tanhf(s);
    }}

    out_left  = out[0];
    out_right = out[1];
}}

}}  // namespace mini_sumo_ai
"""
    path.write_text(header, encoding="ascii")


def main() -> None:
    env = MiniSumoEnv(gui=False, seed=SEED, novamax_level=CURRICULUM[0][0])

    print("Starting NovaMax curriculum from scratch (no checkpoint load)…",
          flush=True)
    model = SAC(
        "MlpPolicy", env,
        policy_kwargs=dict(net_arch=NET_ARCH),
        learning_rate=7.3e-4,
        buffer_size=100_000,
        batch_size=256,
        ent_coef="auto_0.1",
        gamma=0.99,
        verbose=1,
        seed=SEED,
        device="cpu",
    )

    CHECKPOINT_DIR.mkdir(exist_ok=True)
    win_callback = WinRateCallback(report_every=10_000, best_path=BEST_MODEL)
    ckpt_callback = CheckpointCallback(
        save_freq=CHECKPOINT_EVERY,
        save_path=str(CHECKPOINT_DIR),
        name_prefix="sac_actor_novamax",
    )
    callback = CallbackList([win_callback, ckpt_callback])

    try:
        for phase_idx, (level, steps) in enumerate(CURRICULUM, start=1):
            model.get_env().env_method("__setattr__", "novamax_level", level)
            print(
                f"\n--- PHASE {phase_idx}/{len(CURRICULUM)}: "
                f"novamax_level={level}  ({steps} steps) ---",
                flush=True,
            )
            model.learn(
                total_timesteps=steps,
                callback=callback,
                progress_bar=False,
                reset_num_timesteps=False,
            )
    finally:
        env.close()

    if win_callback.total_episodes:
        overall = win_callback.total_wins / win_callback.total_episodes
        recent = (
            sum(win_callback.recent_outcomes) / len(win_callback.recent_outcomes)
            if win_callback.recent_outcomes else 0.0
        )
        print(
            f"\nFine-tune complete: {win_callback.total_wins} wins / "
            f"{win_callback.total_losses} losses ({overall:.2%} overall, "
            f"{recent:.2%} on last {len(win_callback.recent_outcomes)}, "
            f"best torque-weighted score {win_callback.best_wr:.3f})",
            flush=True,
        )

    # Export the BEST tracked snapshot (peak score across phases). Falls
    # back to the final model if a best was never recorded.
    if BEST_MODEL.exists():
        export_model = SAC.load(str(BEST_MODEL), device="cpu")
        # Promote the best to the canonical fine-tuned filename.
        shutil.copy2(BEST_MODEL, OUTPUT_MODEL)
        print(f"Exporting BEST model from {BEST_MODEL.name}.", flush=True)
    else:
        export_model = model
        model.save(str(OUTPUT_MODEL))
        print("No best snapshot — exporting final model.", flush=True)

    export_neural_net(export_model, OUTPUT_HEADER)
    print(
        f"Wrote {OUTPUT_HEADER.name}, {OUTPUT_NPZ.name}, "
        f"{OUTPUT_MODEL.name}, and {BEST_MODEL.name}",
        flush=True,
    )


if __name__ == "__main__":
    main()
